ALTER TABLE cocktail
ALTER
COLUMN glass TYPE VARCHAR(255) USING (glass::VARCHAR(255));

ALTER TABLE cocktail
ALTER
COLUMN id_drink TYPE VARCHAR(255) USING (id_drink::VARCHAR(255));

ALTER TABLE cocktail
ALTER
COLUMN image_link TYPE VARCHAR(255) USING (image_link::VARCHAR(255));

ALTER TABLE cocktail
ALTER
COLUMN ingredients TYPE VARCHAR(255) USING (ingredients::VARCHAR(255));

ALTER TABLE cocktail
ALTER
COLUMN instructions TYPE VARCHAR(255) USING (instructions::VARCHAR(255));

ALTER TABLE cocktail
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE shopping_list
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));